[[redirects]]
  from = "/api/*"
  to = "https://mook-popup-b72570b48977.herokuapp.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
